### PR TITLE
Exit visual mode on indent/unindent

### PR DESCRIPTION
**Pull request by bronson**
First stab at fixing #246

### CODE REVIEW

**Comment by bronson** [comment]
In vim-mode-next 0.54.15.  It appears to work great, including repeating.

There's one difference from Vim: the cursor moves to the beginning of the line instead of remaining where it is.  I can open another issue to address that if desired.

**Comment by maxbrunsfeld** [comment]
Thanks for doing this. 

> the cursor moves to the beginning of the line instead of remaining where it is. I can open another issue to address that if desired

I also noticed that the existing code will not preserve multiple selections/cursors; it destroys all but one cursor afterward by calling `::setSelectedBufferRange()`. It'd be nice to fix both of these things in separate PRs. In the meantime, this looks good. Just waiting on Travis.

**Comment by maxbrunsfeld** [comment]
:tada:

**Comment by jacekkopecky** [comment]
Yay!

**Pull request merged**
