### PR TITLE
Canceling replace

### LINKED ISSUE #549: Exiting replace mode deletes all selected characters
Exiting replace mode currently deletes all selected characters.

**Steps to reproduce:**

1. Enable visual mode (`v`)
2. Select one or more characters
3. Enter replace mode (`r`)
4. Exit replace mode (`Esc`)

**Expected outcome:** Exit replace mode, characters left unchanged
**Current outcome:** Exit replace mode, characters deleted

**Environment:**
- Mac OS X 10.10.2
- Atom 0.186.0
- vim-mode 0.35.0

### PR DESCRIPTION
**Pull request by jacekkopecky**
I’ve tried to test for this but failed, please advise.
Please note the commit comment for a308480 .
Fixes #549 I think.

### CODE REVIEW

**Comment by jacekkopecky** [comment]
I've now added a test, no idea why I couldn't do it the first time around. I think this PR is now good.

**Comment by maletor** [comment]
:dollar:

**Comment by jacekkopecky** [comment]
@maxbrunsfeld is anything holding this PR back? (And a question of GitHub Etiquette which I don't know yet very well: is it all right for me to ask that?)

**Comment by maxbrunsfeld** [comment]
No, I think I just didn't remember to check back once you added the test for it. And yeah, I think it's totally fine GitHub etiquette to ping a maintainer if nobody's responded your PR. Looking...

**Comment by maxbrunsfeld** [comment]
Great! Thanks for this fix.

**Comment by jacekkopecky** [comment]
Super, thank you. 8-)

**Pull request merged**
