### PR TITLE
Text Objects in normal mode without a preceding operator should select text.

### PR DESCRIPTION
**Pull request by mleeds95**
This should close issue #759. But I'm not entirely sure this code is the best way to deal with it so feedback is welcome!

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks for taking the time to fix this! Could you add a spec in [text-objects-spec](https://github.com/atom/vim-mode/blob/master/spec/text-objects-spec.coffee) for this case?

**Comment by jacekkopecky** [comment]
I could see an alternative solution to #759, if you don't mind:

Text Objects are all called `select-<something>` – they could be applicable in any mode to simply select whatever their selection is. This would mean TextObject to have the following single extra line:
```
  execute: -> @select.apply(this, arguments)
```

This way, Text Objects would be extra commands that vim-mode normal mode, and insert mode, doesn't have key bindings for, but they would still be meaningful.

**Comment by mleeds95** [comment]
I agree, @jacekkopecky. I thought this project is trying to mimic vim's functionality, but if we're not bound to that I think that's a better solution.

**Comment by maxbrunsfeld** [comment]
That sounds good.

@mleeds95 do you want to make this change on your branch?

**Comment by mleeds95** [comment]
Yeah I'll rebase and force push.

**Comment by mleeds95** [comment]
This makes the second `instanceof` check on [this line](https://github.com/atom/vim-mode/blob/master/lib/vim-state.coffee#L224) unnecessary. Should we take it out?

**Comment by jacekkopecky** [comment]
I for one would leave it there.

**Comment by mattr-** [comment]
I'm confused. It seems like this is fixing s bug in visual mode, but the description says that it allows text objects to select text in normal mode.

Honestly, it doesn't make much sense for text objects to select text in normal mode. For example, if I type `iw` (The inner word text object) in normal mode in Vim, I enter insert mode and type a 'w'. Does this PR actually change that behavior?

**Comment by mleeds95** [comment]
@mattr- You're right that because the text object commands all start with i or a you would enter insert mode if you use the keyboard shortcuts. But if you execute the commands via the command palette instead (Ctrl + Shift + P) you stay in normal mode and vim-mode currently throws an error. This PR selects the text as if you're in visual mode, although it's debatable if we should just ignore the command.

**Comment by mattr-** [comment]
I feel like we should just ignore the command, since it doesn't actually apply. Maybe the real fix is to set it up so that these are only applicable in operator-pending mode and therefore don't show up in the command palette for normal mode?

**Comment by jacekkopecky** [comment]
@mattr- well, we can say the commands don't apply, or we can ask "could they be useful?" 

Currently, all vim-mode commands are shown in the command palette, even if they don't have key bindings in the current mode (e.g. the text objects in normal mode). Some might genuinely not apply, but I can't see an argument against this particular PR, making text objects select when invoked in normal mode.

**Comment by mattr-** [comment]
If the selection only happens when they're invoked from the command palette, then I can live with that.

**Comment by maxbrunsfeld** [comment]
Thanks @mleeds95; I don't feel strongly about the commands' behavior in normal mode, but it's great to stop this exception from happening to people.

**Pull request merged**
