### PR TITLE
fix issue #521

### PR DESCRIPTION
**Pull request by dnasseri**
Fix issue #521

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks for figuring this out @dnasseri. Could you add a test for this? You should add it somewhere in [this area](https://github.com/atom/vim-mode/blob/2ab86b2942efe6fee81e3d6492ba2020e64ee499/spec/motions-spec.coffee#L1832).

**Comment by dnasseri** [comment]
@maxbrunsfeld absolutely!

**Comment by dnasseri** [comment]
@maxbrunsfeld I'm having a little bit of trouble with getting the spec to fail appropriately

this is the spec I wrote:

    it 'stays put', ->
      editor.setText("\n)")
      editor.setCursorScreenPosition([1, 0])
      expect(-> keydown('%')).not.toThrow();

When I comment out the fix and run `apm test` I see that the error is thrown in the console, but the test does not fail. A bit new to coffeescript. Am I missing something here? Thanks!

**Comment by dnasseri** [comment]
Closing until I fix the spec.

**Pull request closed without merging**
