### PR TITLE
Update to atom 1.0 api (fixes #552)

### LINKED ISSUE #552: Cannot see text input during search

### PR DESCRIPTION
**Pull request by lightsofapollo**
I am usually a heavy (m)vim user but today I tried to play with atom and generally like it... The big bug I hit was not being able to see my search input as I typed.. I am only somewhat confident this makes sense but it looks right given atom core code/deprecation warnings.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Thanks for the PR! It looks like some of the tests are failing. I'll try to look into why when I get a chance.

**Comment by MattKunze** [comment]
#545 has the same changes and I just got the tests to work FWIW. It seems a little ugly how it's traversing the text editor component though

**Comment by bronson** [comment]
Looks like this was fixed by fc24df5be327b1ff7643f648c5f68910231cc7a4?

**Comment by maxbrunsfeld** [comment]
Yeah, this has been taken care of now. Thanks for looking into it though, @lightsofapollo.

**Pull request closed without merging**
