### PR TITLE
backspace over empty `/` now cancels search

### PR DESCRIPTION
**Pull request by shamrin**
see also lloeki/ex-mode#108

### CODE REVIEW

**Comment by nbellowe** [comment]
I like it nice.

**Comment by shamrin** [comment]
Yeah, I was hurt by my Vim habit to cancel search (and ex mode) with backspace. This fixes my pain! What can I do to help merge this PR?

**Comment by 50Wliu** [comment]
@shamrin Can you add some specs for this behavior?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Pull request closed without merging**
