### PR TITLE
till motion should be repeatable with ; (VIM default)

### PR DESCRIPTION
**Pull request by jacekkopecky**
Hi,
VIM has the 'cpoptions' option that directs where VIM should behave like VI; one of the flags is ';':
```
		;	When using |,| or |;| to repeat the last |t| search
			and the cursor is right in front of the searched
			character, the cursor won't move. When not included,
			the cursor would skip over it and jump to the
			following occurrence.
```
This PR implements VIM default behavior where ';' after 't' **does move**.

I haven't realized until today that I've been used to VIM behaviour, as opposed to what VI would do. How about others? Which way would be better in atom/vim-mode?

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
Personally, I'd be ok with either behavior, or even a new setting for this. I'm going to give others some time to weigh in on this one.

**Comment by nicolaiskogheim** [comment]
:+1:

**Comment by jeffschwartz** [comment]
👍

**Comment by maxbrunsfeld** [comment]
Unanimous. Good enough for me. @jacekkopecky I'll merge if you want to rebase this branch onto master or merge master into it.

**Comment by jacekkopecky** [comment]
Thanks, done

**Comment by maxbrunsfeld** [comment]
@jacekkopecky would you mind rebasing this onto master actually? Generally I don't mind a few extra merge commits, but your branch now has 5 merge commits on it.

**Comment by jacekkopecky** [comment]
Sorry @maxbrunsfeld but I've never done rebasing before; is it now as it should be? Or should I maybe go create a new clean branch off of your master and PR that?

**Comment by maxbrunsfeld** [comment]
@jacekkopecky no worries. You should keep your branch and this PR. Probably the simplest thing would be to reset your branch back to your original commit, and then merge master into your branch one final time:

```
git checkout repeat-till-motions

# Make a copy of this branch just in case anything goes wrong
git checkout -b tmp-backup
git checkout repeat-till-motions

git reset --hard 95350b176c5b27f9ffd40f9b1e724aef71951ef9
git fetch atom
git merge atom/master
```

You'll then have to force-push your branch, since you're deleting some commits:

```
git push -f origin repeat-till-motions
```

**Comment by jacekkopecky** [comment]
Thank you!

**Comment by maxbrunsfeld** [comment]
Great. Thanks, @jacekkopecky.

**Pull request merged**
