### PR TITLE
ctrl-a and ctrl-x for increasing/decreasing numbers

### LINKED ISSUE #628: Increment numbers (Ctrl-A + Ctrl-X)
Using `Ctrl-A` to increment numbers and `Ctrl-X` to decrease numbers doesn't seem to be implemented.

### PR DESCRIPTION
**Pull request by jacekkopecky**
fixes #628

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
So happy that this has finally come to pass.

**Comment by maxbrunsfeld** [comment]
:heart:

**Comment by vito** [comment]
omg

:heart_eyes:

**Comment by jacekkopecky** [comment]
Thank you. 8-)

**Comment by maxbrunsfeld** [comment]
@davejacobs might appreciate this one too.

**Comment by davejacobs** [comment]
Yes! (Why? Because macros.)

**Comment by maxbrunsfeld** [comment]
> Why? Because macros.

Which vim-mode lacks right now... but multiple cursors somewhat fill that need.

**Comment by davejacobs** [comment]
Ah interesting - I'll have to try it out

**Comment by slindberg** [comment]
omg thank you thank you thank you :beers:

**Pull request merged**
