### PR TITLE
add `z s` and `z e` horizontal scrolling

### PR DESCRIPTION
**Pull request by jacekkopecky**
This will scroll the window horizontally so that the cursor is at (or near) the left edge of the screen for `z s`, or near the right edge of the screen for `z e`.
Sorry but I've no idea how to test for this behaviour in the specs. Please advise.

### CODE REVIEW

**Comment by dsandstrom** [comment]
Can this be merged?  Seems useful.

**Comment by jacekkopecky** [comment]
I've rebased it to the current status, and finally added tests now; @maxbrunsfeld is there anything holding this one back?

**Comment by jacekkopecky** [comment]
@maxbrunsfeld I've rebased it to master (needed after PR #616), and replaced cursor.autoscroll with the public editor.scrollToCursorPosition, now hopefully it's OK?

**Comment by bronson** [comment]
Hi, here's a fix for the deprecation errors: https://github.com/bronson/vim-mode-next/commit/ff112292534e7b9d2a4a5fb52db2ba7a6da7a273

Looks good.  With the deprecations fixed, I vote for merging it.

**Comment by jacekkopecky** [comment]
@bronson how do you get deprecation errors, please? I can't seem to see any when I run tests in this PR's branch with the current vim-mode master merged in.

**Comment by jacekkopecky** [comment]
Ah, #738 – sorry, I went through my email in reverse order.

**Comment by maxbrunsfeld** [comment]
:ok_hand: Looks great; sorry for not responding to this one.

**Pull request merged**
