### PR TITLE
:bug: Hide find-and-replace panels when resetting to normal mode.

### LINKED ISSUE #165: Search box doesn't hide with escape
If using vim-mode and cmd-shift-f or cmd-f. After bringing the search box up and then focusing on the file the escape key does not hide the search box. It all works fine if vim-mode is disabled.

Also the block cursor in vim-mode disappeared after the last update. I'm not sure if you guys just removed that because you think the editor is cooler without it but definitely you should bring it back. The block cursor is awesome.

### PR DESCRIPTION
**Pull request by jeremychase**
This PR is an attempt to resolve [this issue](https://github.com/atom/vim-mode/issues/165) while interacting with the find-and-replace package. ~~This is dependent on [this other PR](https://github.com/atom/find-and-replace/pull/535) in the `find-and-replace` package.~~ _(This PR is no longer dependent on any other PRs.)_

I am unsure how to test that this activation is being dispatched correctly so feedback is appreciated.

### CODE REVIEW

**Comment by JeremyChase** [comment]
As per [benogle's](https://github.com/benogle) [comment](https://github.com/atom/find-and-replace/pull/535#issuecomment-144876936) I have switched to using `core:cancel` from `vim-mode`. Any issues with this?

**Comment by JeremyChase** [comment]
@maxbrunsfeld I saw you have recently made commits to `vim-mode`. What is the next step to have this PR reviewed?

**Comment by stv8** [comment]
+1 get this into Atom!

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Pull request closed without merging**
