### PR TITLE
Fix some scroll bugs

### LINKED ISSUE #961: Soft Wrap impacts page down command
The [half page down](http://vimhelp.appspot.com/scroll.txt.html#CTRL-D) and [page down](http://vimhelp.appspot.com/scroll.txt.html#CTRL-F) appear to be impacted negatively by the Atom "Soft Wrap" preference. I originally reported this issue in [#941](https://github.com/atom/vim-mode/issues/941#issuecomment-170930772), but I'm not sure it's related in actuality. [This is the file](https://gist.github.com/dcalhoun/ff4984e06fa4d4f40d00) I've been using for testing.

#### Behavior
As a user, I press and hold <kbd>ctrl</kbd> + <kbd>f</kbd> or <kbd>ctrl</kbd> + <kbd>d</kbd>.

#### Expected Outcome
The editor scrolls for as long as I hold the keys, until reaching the end of the document. The line numbers update accordingly. The cursor is visible throughout.

#### Current Outcome
The editor scrolls two pages. The line numbers update accordingly for the first two pages. The cursor disappears immediately.

#### Environment
- Mac OS X 10.11.3 (15D21)
- Atom v.1.4.3
- Preferred Line Length (100)
- Soft Wrap (enabled)
- Soft Wrap At Preferred Line Length (enabled)

### PR DESCRIPTION
**Pull request by b6pzeusbc54tvhw5jgpyw8pwz2x6gs**
Fix #961

### CODE REVIEW

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I think that the issue #961 is the critical UI problem in vim-mode.
When I work markdown using vim-mode, that bug makes me unhappy.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I have a question. What do you mean by a `needs-review` label? What can i do for reviewing this issue?

**Comment by 50Wliu** [comment]
@b6pzeusbc54tvhw5jgpyw8pwz2x6gs it just means someone from the Atom team has to review this.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Thanks for answer. I plan to pull-request again.
The new PR will have more details and a better code. So I closed this PR.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Thanks for answer. I plan to pull-request again.
The new PR will have more details and a better code. So I closed this PR.

**Pull request closed without merging**
