### PR TITLE
beep when search history is exhausted

### PR DESCRIPTION
**Pull request by coolwanglu**

### CODE REVIEW

**Comment by coolwanglu** [comment]
Do we want beeping in vim-mode? I could add lots more (moving up over the first line etc).

**Comment by jeffschwartz** [comment]
I'd only like it if it is an option and I can turn it off via options. Otherwise I'd view it as intrusive. No offense intended of course :)

**Comment by coolwanglu** [comment]
@jeejkang  There's an option for atom to turn of beeping globally. But of course we can make a vim-mode-only option.

**Comment by bronson** [comment]
I don't quite get it...  Stock vim doesn't beep when you've exhausted search history (renamed my ~/.vim directory and launched with `vim -u /dev/null` so I think it's stock).

Atom doesn't seem to either.  (hitting cmd-f, then up-arrow until it stops...  no beep)

The patch looks great but is there a precedent for this feature?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!

**Pull request closed without merging**
