### PR TITLE
Add subword movement support

### PR DESCRIPTION
**Pull request by deiwin**
I will be fleshing out some ideas for #377 in this PR. Comments and feedback are welcome. When all of the main changes are made and you agree and are happy with them, I can clean up the commit history and add the necessary documentation etc.

The general idea is that there will be 3 different definitions of a word. The main one, an alternative one and the space delimited (*WORD*) one. The only difference between the main and the alt one would be that one of them would be sensitive to camel (and snake?) casing and the other would not.

TODO:
 - [x] add a configuration option that says whether a CamelCase sensitive or insensitive definition of a *word* is used by default
 - [ ] add an alternative version for the <kbd>w</kbd> movement
   - [ ] revert or re-fix https://github.com/atom/atom/commit/ba3ab41
   - [ ] fix the tests that fail when <kbd>Alt</kbd> is used as a modifier
   - [ ] wait until atom/atom#7658 has been fixed and see if it fixes the already added tests
 - [ ] add an alternative version for the <kbd>b</kbd> movement
 - [ ] add an alternative version for the <kbd>e</kbd> movement
 - [ ] add an alternative version for the <kbd>w</kbd> text object
 - [ ] **?** add an alternative version for the <kbd>Ctrl</kbd>-<kbd>w</kbd> binding in the insert mode

### CODE REVIEW

**Comment by deiwin** [comment]
atom/atom@ba3ab41 from atom/atom#7612 makes the subword regex match line endings if there's any trailing whitespace and line beginnings if it's followed by any whitespace. I currently worked around it, but I think the regex should be changed.

**Comment by deiwin** [comment]
Can someone help me figure out why some of the tests fail when I use alt as a modifier. They seem to work just fine when actually used. I tried messing around with the way the spec-helper dispatches keyboard events, but to no avail.

**Comment by jacekkopecky** [comment]
This is a guess: it seems to me that CI is complaining about the presence of focused specs. Please try changing `fdescribe` to `describe`.

**Comment by jacekkopecky** [comment]
I like the procedurally generated tests with `itMovesByWord` and `itMovesBySubWord`, by the way!

**Comment by deiwin** [comment]
I'd kept the focused specs because I hadn't really gotten them to pass on my own machine yet and wasn't worrying too much about the CI build. I added a commit to change that now, however, so that the CI logs would show the actual problem I'm facing.

**Comment by deiwin** [comment]
Not working on this anymore

**Pull request closed without merging**
